### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by egorpugin** [Arryboom/fmemopen_windows#1]
Hi,

You don't have `#include "libfmemopen.h"` in your .c file.
Because of this I see linker error.
Compiler cannot match those declaration with definition in static library.

```
error LNK2019: unresolved external symbol "struct _iobuf * __cdecl fmemopen(void *,unsigned __int64,char const *)" (?fmemopen@@YAPEAU_iobuf@@PEAX_KPEBD@Z) referenced in function
```

**Comment by egorpugin** [comment]
More of that, you must include `<stdio.h> into .h file to make FILE visible in declaration.

**Comment by Arryboom** [comment]
> More of that, you must include `<stdio.h> into .h file to make FILE visible in declaration.

sry just got alert from github about this issue,just tested on vs2019,works fine,which .c file do you mean specifically? main.c is not needed in this project and I forgot to delete,it was just a  temp file for testing

**Comment by egorpugin** [comment]
`#include "libfmemopen.h"` should be added into `libfmemopen.c`.
`#include <stdio.h>` should be added into `libfmemopen.h`.

**Comment by Arryboom** [comment]
> `#include "libfmemopen.h"` should be added into `libfmemopen.c`. `#include <stdio.h>` should be added into `libfmemopen.h`.

Thanks,seems this only affecting mingw32 compiler toolsets,fix released.
Also,on cpp series usage u might want add extern "C" keyword to header.
